[client]
showErrorDetails = false
toolbarMode = "viewer"

[theme]
base ="light"
primaryColor ="#0C344D"
backgroundColor = "white"
secondaryBackgroundColor = "#e4f2e5"
textColor ="#0C344D"
font = "serif"